#!/usr/bin/env python3
"""Regenerate the root import files EG.lean, EGTest.lean and EGCheck.lean from the module files
on disk (EGCheck.Final is excluded: it is built separately and fails until phase P4)."""
import os
import sys
if __name__ == "__main__" and not sys.flags.isolated:
    # Never import from the script or the working directory (trust2.opus N2/N3): re-run as python3 -I.
    os.execv(sys.executable, [sys.executable, "-I"] + sys.argv)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def mods(d, exclude=()):
    out = []
    for dirpath, _, files in os.walk(os.path.join(ROOT, d)):
        for f in files:
            if f.endswith(".lean"):
                m = os.path.relpath(os.path.join(dirpath, f), ROOT)[:-5].replace(os.sep, ".")
                if m not in exclude:
                    out.append(m)
    return sorted(out)


def main():
    eg = mods("EG")
    with open(os.path.join(ROOT, "EG.lean"), "w") as fh:
        fh.write("module\n\n" + "".join(f"public import {m}\n" for m in eg))
        fh.write("\n/-! Root of the `EG` library (generated by scripts/gen_roots.py). -/\n")
    t = mods("EGTest")
    with open(os.path.join(ROOT, "EGTest.lean"), "w") as fh:
        fh.write("".join(f"import {m}\n" for m in t))
        fh.write("\n/-! Root of the `EGTest` library (generated by scripts/gen_roots.py). -/\n")
    c = mods("EGCheck", exclude=("EGCheck.Final",))
    with open(os.path.join(ROOT, "EGCheck.lean"), "w") as fh:
        fh.write("".join(f"import {m}\n" for m in c))
        fh.write("\n/-! Root of the check library (generated by scripts/gen_roots.py). The final check\n"
                 "`EGCheck.Final` is built separately (`lake build EGCheck.Final`) and fails until P4. -/\n")
    print(f"EG: {len(eg)} modules, EGTest: {len(t)}, EGCheck: {len(c)}")


if __name__ == "__main__":
    main()
