#!/usr/bin/env python3
"""Sorry frontier, dashboard and ratchet (PLAN_FORMALIZATION.md §4 `eg_status`).

    scripts/status.py            # recompute status/frontier.json and status/STATUS.md
    scripts/status.py --check    # also enforce the ratchet if status/ratchet.json says so
    scripts/status.py --check --no-write
        # read-only: compute and enforce, print the dashboard to stdout, write NO file. Used by the
        # workflows, which run from the read-only snapshot of scripts/pristine.sh (trust3.fable §3.5:
        # as a non-root user the old unconditional write failed with EACCES).

The frontier is the set of declarations under `EG` whose axioms include `sorryAx`.
Ratchet (enforced from phase P3): the frontier may only shrink relative to the committed
`status/frontier.json`. Modules must be built first (`lake build EG`).
"""
import os
import sys
if __name__ == "__main__" and not sys.flags.isolated:
    # Never import from the script or the working directory (trust2.opus N2/N3): re-run as python3 -I.
    os.execv(sys.executable, [sys.executable, "-I"] + sys.argv)
import collections
import json
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATUS = os.path.join(ROOT, "status")


def modules():
    mods = []
    for dirpath, _, files in os.walk(os.path.join(ROOT, "EG")):
        for f in files:
            if f.endswith(".lean"):
                rel = os.path.relpath(os.path.join(dirpath, f), ROOT)[:-5]
                mods.append(rel.replace(os.sep, "."))
    return sorted(mods)


def main():
    check = "--check" in sys.argv
    no_write = "--no-write" in sys.argv
    unknown = [a for a in sys.argv[1:] if a not in ("--check", "--no-write")]
    if unknown:
        sys.exit(f"status: unknown argument(s) {unknown}")
    cmd = ["lake", "env", "lean", "--run", "scripts/Axioms.lean", "--json", "--prefix", "EG"]
    cmd += modules()
    res = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
    recs = [json.loads(l) for l in res.stdout.splitlines() if l.startswith("{")]
    if not recs and res.returncode != 0:
        sys.stderr.write(res.stderr)
        sys.exit("status: scripts/Axioms.lean failed (are the modules built?)")
    frontier = sorted(r["name"] for r in recs if r["sorry"])
    violations = [r for r in recs if r["violations"]]
    per_mod = collections.Counter(r["module"] for r in recs if r["sorry"])
    total_mod = collections.Counter(r["module"] for r in recs)
    old = []
    fpath = os.path.join(STATUS, "frontier.json")
    if os.path.exists(fpath):
        with open(fpath) as fh:
            old = json.load(fh)
    grown = sorted(set(frontier) - set(old))
    enforce = False
    rpath = os.path.join(STATUS, "ratchet.json")
    if os.path.exists(rpath):
        with open(rpath) as fh:
            enforce = json.load(fh).get("enforce", False)
    lines = ["# Formalization status (generated by scripts/status.py; do not edit)", "",
             f"- constants inspected: {len(recs)}",
             f"- sorry frontier (constants depending on sorryAx): {len(frontier)}",
             f"- axiom/trust violations: {len(violations)}",
             f"- ratchet enforced: {enforce}", "", "| module | constants | using sorry |",
             "|---|---|---|"]
    for m in sorted(total_mod):
        lines.append(f"| {m} | {total_mod[m]} | {per_mod.get(m, 0)} |")
    if no_write:
        print("\n".join(lines))
    else:
        os.makedirs(STATUS, exist_ok=True)
        with open(os.path.join(STATUS, "STATUS.md"), "w") as fh:
            fh.write("\n".join(lines) + "\n")
    if check and enforce and grown:
        for g in grown:
            print("RATCHET: new sorry-dependent declaration", g)
        sys.exit(1)
    if not no_write:
        with open(fpath, "w") as fh:
            json.dump(frontier, fh, indent=1)
            fh.write("\n")
    for v in violations:
        print("VIOLATION", v["name"], v["axioms"])
    print(f"status: {len(recs)} constants, frontier {len(frontier)} (was {len(old)}), "
          f"{len(violations)} violations")
    sys.exit(1 if violations else 0)


if __name__ == "__main__":
    main()
