import EGCheck.Bridge
import EGCheck.BridgeCore
import EGCheck.BridgeLemmas

/-! Root of the check library (generated by scripts/gen_roots.py). The final check
`EGCheck.Final` is built separately (`lake build EGCheck.Final`) and fails until P4. -/
